# Generated by Django 4.1.2 on 2023-05-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='komoditas',
            fields=[
                ('id_komoditas', models.AutoField(primary_key=True, serialize=False)),
                ('nama_komoditas', models.CharField(max_length=50)),
                ('satuan', models.IntegerField()),
                ('kode_grade', models.CharField(max_length=50)),
                ('harga_sewa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mitra',
            fields=[
                ('id_mitra', models.AutoField(primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=30)),
                ('alamat_mitra', models.TextField(blank=True, null=True)),
                ('nomor_mitra', models.PositiveIntegerField()),
                ('tanggal_mulai_mitra', models.DateField()),
                ('durasi_kontrak', models.PositiveIntegerField()),
                ('luas_lahan', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pembeli',
            fields=[
                ('id_pembeli', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pembeli', models.CharField(max_length=30)),
                ('nomor_pembeli', models.PositiveIntegerField()),
                ('alamat_pembeli', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='produk',
            fields=[
                ('id_produk', models.AutoField(primary_key=True, serialize=False)),
                ('namaproduk', models.CharField(max_length=15)),
                ('satuanproduk', models.CharField(max_length=15)),
                ('hargaproduk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaksi_lain',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_transaksi', models.CharField(max_length=50)),
                ('tanggal_transaksi', models.DateField()),
                ('biaya', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='penjualan',
            fields=[
                ('id_penjualan', models.AutoField(primary_key=True, serialize=False)),
                ('tanggalpenjualan', models.DateField()),
                ('idpembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.pembeli')),
            ],
        ),
        migrations.CreateModel(
            name='panen',
            fields=[
                ('id_panen', models.AutoField(primary_key=True, serialize=False)),
                ('biaya_pembelian', models.IntegerField()),
                ('tanggal_panen', models.DateField()),
                ('id_mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.mitra')),
            ],
        ),
        migrations.CreateModel(
            name='detail_panen',
            fields=[
                ('id_detailpanen', models.AutoField(primary_key=True, serialize=False)),
                ('jumlahpanen', models.IntegerField()),
                ('tanggalkadaluwarsa', models.DateField()),
                ('idkomoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.komoditas')),
                ('idpanen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.panen')),
            ],
        ),
        migrations.CreateModel(
            name='detail_jual',
            fields=[
                ('id_detailjual', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('id_penjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.penjualan')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.produk')),
            ],
        ),
    ]
