# Generated by Django 4.1.6 on 2023-06-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan',
            name='idpembeli',
        ),
        migrations.DeleteModel(
            name='pembeli',
        ),
    ]
