# Generated by Django 4.1.6 on 2023-06-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0002_remove_penjualan_idpembeli_delete_pembeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='grade',
            fields=[
                ('id_grade', models.AutoField(primary_key=True, serialize=False)),
                ('nama_grade', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='komoditas',
            name='kode_grade',
        ),
        migrations.CreateModel(
            name='detail_komoditas',
            fields=[
                ('id_detailkomoditas', models.AutoField(primary_key=True, serialize=False)),
                ('harga_beli', models.IntegerField()),
                ('harga_jual', models.IntegerField()),
                ('id_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.grade')),
                ('id_komoditas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guava.komoditas')),
            ],
        ),
    ]
