# Generated by Django 4.1.6 on 2023-06-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0003_grade_remove_komoditas_kode_grade_detail_komoditas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panen',
            name='biaya_pembelian',
        ),
    ]
