# Generated by Django 4.1.6 on 2023-06-27 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0004_remove_panen_biaya_pembelian'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='deskripsi',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
