# Generated by Django 4.1.6 on 2023-06-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0005_grade_deskripsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='komoditas',
            name='harga_sewa',
        ),
        migrations.RemoveField(
            model_name='komoditas',
            name='satuan',
        ),
    ]
