# Generated by Django 4.1.6 on 2023-06-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guava', '0006_remove_komoditas_harga_sewa_remove_komoditas_satuan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_panen',
            name='idkomoditas',
        ),
        migrations.AddField(
            model_name='detail_panen',
            name='id_detailkomoditas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guava.detail_komoditas'),
            preserve_default=False,
        ),
    ]
